export const USER = "user";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_REQUEST_SUCCESS = "LOGIN_REQUEST_SUCCESS";
export const LOGIN_REQUEST_FAILURE = "LOGIN_REQUEST_FAILURE";

export const SIGNUP_REQUEST = "SIGNUP_REQUEST"
export const SIGNUP_REQUEST_SUCCESS = "SIGNUP_REQUEST_SUCCESS"
export const SIGNUP_REQUEST_FAILURE = "SIGNUP_REQUEST_FAILURE";

export const PROFILE_REQUEST = "PROFILE_REQUEST";
export const PROFILE_REQUEST_SUCCESS = "PROFILE_REQUEST_SUCCESS";
export const PROFILE_REQUEST_FAILURE = "PROFILE_REQUEST_FAILURE";

export const PROFILE_UPDATE_REQUEST = "PROFILE_UPDATE_REQUEST";
export const PROFILE_UPDATE_SUCCESS = "PROFILE_UPDATE_SUCCESS";
export const PROFILE_UPDATE_FAILURE = "PROFILE_UPDATE_FAILURE";
